-- The Attributes we want returned from the query
SELECT
    p.PROPERTY_ID ,
    p.ADDRESS,
    RESIDENT_ID,
	r.FIRST_NAME,
	r.SURNAME,
    P.MONTHLY_RENT * 12 AS ANN_RENT,
	P.SQR_FT
FROM
    property p 
-- Query requires data from multiple tables
INNER JOIN
    RESIDENTS R ON p.PROPERTY_ID = R.PROPERTY_ID

INNER JOIN PROPERTY PR ON P.OFFICE_NUM = PR.OFFICE_NUM
LEFT JOIN OWNER O ON P.OWNER_NUM = O.OWNER_NUM
RIGHT JOIN OFFICE OFI ON P.OFFICE_NUM = OFI.OFFICE_NUM
-- Conditions on the attributes that must be followed 
WHERE
-- Will return the top 3 property IDs then that is intersected with the property ID's from residents returning only the like property IDs
	P.PROPERTY_ID IN (SELECT TOP 3 PROPERTY_ID 
						FROM SERVICE_REQUEST
							WHERE STATUS IS NOT NULL 
							
							INTERSECT 

							SELECT R.PROPERTY_ID
								FROM RESIDENTS)
-- Monthly rent must fall between those rents and sqr ft of the property must be greater than all properties where sqr ft is greater than 800
    OR (P.MONTHLY_RENT BETWEEN 1200 AND 2500
    AND P.SQR_FT > ALL (SELECT P.SQR_FT
							FROM PROPERTY P
								WHERE P.SQR_FT BETWEEN 800 AND 1000)) 
-- Nested Query to get rid of any owners from Washington
	OR p.OWNER_NUM IN (SELECT O.OWNER_NUM
							FROM OWNER
								WHERE NOT STATE = 'WA'
								
								UNION
								
								SELECT ADDRESS
									FROM PROPERTY
										WHERE EXISTS (SELECT R.PROPERTY_ID
															FROM RESIDENTS CROSS JOIN PROPERTY
																WHERE FIRST_NAME IS NOT NULL
																AND SURNAME LIKE '%%'))
														
-- How the results will be grouped up with each other
GROUP BY
    p.PROPERTY_ID,
    p.ADDRESS,
    RESIDENT_ID,
	r.FIRST_NAME,
	r.SURNAME,
    P.MONTHLY_RENT,
	P.SQR_FT
-- Conditions that apply to the group by statement
HAVING
    AVG(P.SQR_FT) > 1000
    AND COUNT(DISTINCT RESIDENT_ID) >= 1
-- Formats the outputted data
ORDER BY
  p.PROPERTY_ID ASC;

   



/* 
SELECT THE PROPERTY ID, ADDRESS OF THE PROPERTY, RESIDENT ID, RESIDENT NAME, SQUARE FEET, AND THE ANNUAL RENT OF ALL PROPERTIES (MAKE SURE YOU NAME THE COLUMN)
WE ONLY WANT THE ANNUAL RENTS RETURNED OF PROPERTIES WHERE THE RENT IS GREATER THAN $1200 BUT LESS THAN $2501 AND THE SQR FT IS GREATER THAN ALL PROPERTIES WHERE THE SQR FT IS GREATER THAN 800 AND LESS THAN 1001
OR RETURN THE OWNER NUM ON A TABLE COMPRISED OF ALL RECORDS FROM OWNER WHERE THE STATE IS NOT WASHINGTON AND THE ADDRESS FROM PROPERTY THAT EXISTS IN A PRODUCT OF RESIDENTS AND PROPERTY 
WHERE THERE IS A FIRST NAME ENTRY AND SURNAME SHOULD CONTAIN ANYTHING. 
ONLY THE PROPERTY ID SHOULD BE SELECTED FROM THIS PRODUCT.
THE RESULTS SHOULD BE ON THE COUNT OF THE RESIDENT ID WHERE EACH ID SHOWS ONLY ONCE, THE ID SHOULD BE GREATER THAN OR EQUAL TO 1 AND THE AVG SQR IS GREATER THAN 1000
THEN ORDER THEM BASED ON THE PROPERTY ID IN ASCENDING ORDER
*/